server:
  port: 8060

eureka:
  instance:
    hostname: gateway-service
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://discovery-service:8061/eureka/
  server:
    enable-self-preservation: false
    
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: employee-service
        uri: http://employee-service:8090
        predicates:
        - Path=/employee/**
        filters:
        - RewritePath=/employee/(?<path>.*), /$\{path}
        - name: Hystrix
          args:
            name: default
            fallbackUri: forward:/hystrixfallback
      - id: department-service
        uri: http://department-service:8091
        predicates:
        - Path=/department/**
        filters:
        - RewritePath=/department/(?<path>.*), /$\{path}
        - name: Hystrix
          args:
            name: default
            fallbackUri: forward:/hystrixfallback
      - id: organization-service
        uri: http://organization-service:8092
        predicates:
        - Path=/organization/**
        filters:
        - RewritePath=/organization/(?<path>.*), /$\{path}
        - name: Hystrix
          args:
            name: default
            fallbackUri: forward:/hystrixfallback
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 20000
